/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laboratorio3;

import static Laboratorio3.AlgoritmosRecursivos.invertirPalabra;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class PanelLab3Ejercicio2 extends javax.swing.JPanel {

    /**
     * Creates new form PanelLab3Ejercicio2
     */
    public PanelLab3Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField_MostrarArray = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ingresaArray = new javax.swing.JTextField();

        setBackground(new java.awt.Color(232, 232, 232));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel2.setText("Palabra inversa");

        jTextField_MostrarArray.setEditable(false);
        jTextField_MostrarArray.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jTextField_MostrarArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MostrarArrayActionPerformed(evt);
            }
        });

        btnConvertir.setBackground(new java.awt.Color(226, 226, 226));
        btnConvertir.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setBorderPainted(false);
        btnConvertir.setContentAreaFilled(false);
        btnConvertir.setFocusable(false);
        btnConvertir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConvertir.setOpaque(true);
        btnConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConvertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConvertirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConvertirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConvertirMouseReleased(evt);
            }
        });
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel1.setText("Ingrese la Palabra");

        jTextField_ingresaArray.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jTextField_ingresaArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ingresaArrayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConvertir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jTextField_ingresaArray, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_MostrarArray, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField_ingresaArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField_MostrarArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MostrarArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MostrarArrayActionPerformed

    }//GEN-LAST:event_jTextField_MostrarArrayActionPerformed

    private void btnConvertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMouseEntered
        btnConvertir.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnConvertirMouseEntered

    private void btnConvertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMouseExited
        btnConvertir.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnConvertirMouseExited

    private void btnConvertirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMousePressed
        btnConvertir.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnConvertirMousePressed

    private void btnConvertirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMouseReleased
        btnConvertir.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnConvertirMouseReleased

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed

        String palabra = jTextField_ingresaArray.getText(); //obtenemos lo que se ingresa
        jTextField_MostrarArray.setText(invertirPalabra(palabra));
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void jTextField_ingresaArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ingresaArrayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ingresaArrayActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField_MostrarArray;
    private javax.swing.JTextField jTextField_ingresaArray;
    // End of variables declaration//GEN-END:variables
}
