
package Laboratorio3;

import static Laboratorio3.AlgoritmosRecursivos.ulam;
import java.awt.Color;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PanelLab3Ejercicio6 extends javax.swing.JPanel {

    /**
     * Creates new form PanelLab3Ejercicio6
     */
    public PanelLab3Ejercicio6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_ingresaNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MostrarSecuencia = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel1.setText("Ingrese el numero :");

        jTextField_ingresaNum.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jTextField_ingresaNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ingresaNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel2.setText("Secuencia ULAM");

        jTextField_MostrarSecuencia.setEditable(false);
        jTextField_MostrarSecuencia.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jTextField_MostrarSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MostrarSecuenciaActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(226, 226, 226));
        btnCalcular.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setFocusable(false);
        btnCalcular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCalcular.setOpaque(true);
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalcularMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCalcularMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCalcularMouseReleased(evt);
            }
        });
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_MostrarSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_ingresaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ingresaNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField_MostrarSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ingresaNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ingresaNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ingresaNumActionPerformed

    private void jTextField_MostrarSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MostrarSecuenciaActionPerformed

    }//GEN-LAST:event_jTextField_MostrarSecuenciaActionPerformed

    private void btnCalcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseEntered
        btnCalcular.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnCalcularMouseEntered

    private void btnCalcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseExited
        btnCalcular.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnCalcularMouseExited

    private void btnCalcularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMousePressed
        btnCalcular.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnCalcularMousePressed

    private void btnCalcularMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseReleased
        btnCalcular.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnCalcularMouseReleased

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        String CadenaArray = jTextField_ingresaNum.getText(); //obtenemos lo que se ingresa
        int num = 0;
        try
        {
             num = Integer.parseInt(CadenaArray); 
             String mensaje = "";
             jTextField_MostrarSecuencia.setText(ulam(num, mensaje) + "1");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ingrese solo valores enteros");
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField_MostrarSecuencia;
    private javax.swing.JTextField jTextField_ingresaNum;
    // End of variables declaration//GEN-END:variables
}
