package interfaz;

/**
 *
 * @author Usuario
 */
import java.awt.*;
import javax.swing.JPanel;

public class main extends javax.swing.JFrame {

    
    /**
     * Creates new form Ejercicio1
     */
    public main() {
        initComponents();
        setLocationRelativeTo(null);
        
        /*
          al inicialiazar el jframe elegimos las cosas vibles y las que no
        */
        btnLaboratorio1.setVisible(false);
        btnLaboratorio2.setVisible(false);
        btnLaboratorio3.setVisible(false);
        btnLaboratorio4.setVisible(false);
        btnLaboratorio5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAzul = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLaboratorios = new javax.swing.JButton();
        btnLaboratorio1 = new javax.swing.JButton();
        btnLaboratorio2 = new javax.swing.JButton();
        btnLaboratorio3 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnLaboratorio4 = new javax.swing.JButton();
        btnLaboratorio5 = new javax.swing.JButton();
        PanelContencion = new javax.swing.JPanel();
        PanelPresentacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAzul.setBackground(new java.awt.Color(0, 55, 145));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Consolas", 0, 16));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html><b>Universidad Nacional <br>de Ingeniería (UNI)</html>");

        btnLaboratorios.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorios.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconMenu.png"))); // NOI18N
        btnLaboratorios.setText("Laboratorios");
        btnLaboratorios.setBorderPainted(false);
        btnLaboratorios.setContentAreaFilled(false);
        btnLaboratorios.setFocusable(false);
        btnLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorios.setOpaque(true);
        btnLaboratorios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconMenu.png"))); // NOI18N
        btnLaboratorios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconMenuApagado.png"))); // NOI18N
        btnLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseReleased(evt);
            }
        });
        btnLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratoriosActionPerformed(evt);
            }
        });

        btnLaboratorio1.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorio1.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorio1.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorio1.setText("Laboratorio 1");
        btnLaboratorio1.setBorderPainted(false);
        btnLaboratorio1.setContentAreaFilled(false);
        btnLaboratorio1.setFocusable(false);
        btnLaboratorio1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorio1.setOpaque(true);
        btnLaboratorio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratorio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratorio1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorio1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratorio1MouseReleased(evt);
            }
        });
        btnLaboratorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorio1ActionPerformed(evt);
            }
        });

        btnLaboratorio2.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorio2.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorio2.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorio2.setText("Laboratorio 2");
        btnLaboratorio2.setBorderPainted(false);
        btnLaboratorio2.setContentAreaFilled(false);
        btnLaboratorio2.setFocusable(false);
        btnLaboratorio2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorio2.setOpaque(true);
        btnLaboratorio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratorio2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratorio2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorio2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratorio2MouseReleased(evt);
            }
        });
        btnLaboratorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorio2ActionPerformed(evt);
            }
        });

        btnLaboratorio3.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorio3.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorio3.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorio3.setText("Laboratorio 3");
        btnLaboratorio3.setBorderPainted(false);
        btnLaboratorio3.setContentAreaFilled(false);
        btnLaboratorio3.setFocusable(false);
        btnLaboratorio3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorio3.setOpaque(true);
        btnLaboratorio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratorio3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratorio3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorio3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratorio3MouseReleased(evt);
            }
        });
        btnLaboratorio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorio3ActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 55, 145));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_uni_blanco.png"))); // NOI18N
        btnInicio.setContentAreaFilled(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnInicio.setVerifyInputWhenFocusTarget(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnLaboratorio4.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorio4.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorio4.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorio4.setText("Laboratorio 4");
        btnLaboratorio4.setBorderPainted(false);
        btnLaboratorio4.setContentAreaFilled(false);
        btnLaboratorio4.setFocusable(false);
        btnLaboratorio4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorio4.setOpaque(true);
        btnLaboratorio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratorio4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratorio4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorio4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratorio4MouseReleased(evt);
            }
        });
        btnLaboratorio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorio4ActionPerformed(evt);
            }
        });

        btnLaboratorio5.setBackground(new java.awt.Color(1, 50, 170));
        btnLaboratorio5.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnLaboratorio5.setForeground(new java.awt.Color(255, 255, 255));
        btnLaboratorio5.setText("Laboratorio 5");
        btnLaboratorio5.setBorderPainted(false);
        btnLaboratorio5.setContentAreaFilled(false);
        btnLaboratorio5.setFocusable(false);
        btnLaboratorio5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaboratorio5.setOpaque(true);
        btnLaboratorio5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaboratorio5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaboratorio5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaboratorio5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLaboratorio5MouseReleased(evt);
            }
        });
        btnLaboratorio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorio5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAzulLayout = new javax.swing.GroupLayout(PanelAzul);
        PanelAzul.setLayout(PanelAzulLayout);
        PanelAzulLayout.setHorizontalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLaboratorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAzulLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLaboratorio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaboratorio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaboratorio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAzulLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addComponent(btnLaboratorio4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaboratorio5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnInicio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelAzulLayout.setVerticalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaboratorios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaboratorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaboratorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaboratorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaboratorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaboratorio5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(PanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 560));

        PanelContencion.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout PanelContencionLayout = new javax.swing.GroupLayout(PanelContencion);
        PanelContencion.setLayout(PanelContencionLayout);
        PanelContencionLayout.setHorizontalGroup(
            PanelContencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelContencionLayout.setVerticalGroup(
            PanelContencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(PanelContencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 600, 430));

        PanelPresentacion.setBackground(new java.awt.Color(216, 216, 216));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 16));
        jLabel1.setText("<html><b>Bienvenido al gestor de laboratorios<br><center>de la asignatura de AED<center></br>Algoritmización y Estructuras de Datos</html>");

        javax.swing.GroupLayout PanelPresentacionLayout = new javax.swing.GroupLayout(PanelPresentacion);
        PanelPresentacion.setLayout(PanelPresentacionLayout);
        PanelPresentacionLayout.setHorizontalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        PanelPresentacionLayout.setVerticalGroup(
            PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(PanelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 600, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //en este evento hacemos la funcion: cuando el cursor pase por el boton cambie de color
    private void btnLaboratoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseEntered
        btnLaboratorios.setBackground(new Color(59,89,152));   
    }//GEN-LAST:event_btnLaboratoriosMouseEntered
    
    //en este evento hacemos la funcion: cuando el cursor salga del area del boton cambie de color, 
    //en este caso al color de fondo del panel
    private void btnLaboratoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseExited
       btnLaboratorios.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratoriosMouseExited
    
    //en este evento hacemos la funcion: cuando se presione el mause dentro del boton cambie al color de fondo del panel
    private void btnLaboratoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMousePressed
        btnLaboratorios.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratoriosMousePressed

    //En este evento haceos la funcion: cuando se deje de presionar el mause dentro del boton, cambiamos al nuevo color para hacer efecto hover
    private void btnLaboratoriosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseReleased
        btnLaboratorios.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratoriosMouseReleased

    private void btnLaboratorio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio1MouseEntered
        btnLaboratorio1.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio1MouseEntered

    private void btnLaboratorio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio1MouseExited
        btnLaboratorio1.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio1MouseExited

    private void btnLaboratorio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio1MousePressed
        btnLaboratorio1.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio1MousePressed

    private void btnLaboratorio1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio1MouseReleased
        btnLaboratorio1.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio1MouseReleased

    /*
       Sentencias que se ejecutaran al presionar el boton
    */
    private void btnLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratoriosActionPerformed
           
        btnLaboratorio1.setVisible(true);
        btnLaboratorio2.setVisible(true);
        btnLaboratorio3.setVisible(true);
        btnLaboratorio4.setVisible(true);
        btnLaboratorio5.setVisible(true);
    }//GEN-LAST:event_btnLaboratoriosActionPerformed

    private void btnLaboratorio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio2MouseEntered
        btnLaboratorio2.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio2MouseEntered

    private void btnLaboratorio2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio2MouseExited
        btnLaboratorio2.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio2MouseExited

    private void btnLaboratorio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio2MousePressed
        btnLaboratorio2.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio2MousePressed

    private void btnLaboratorio2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio2MouseReleased
        btnLaboratorio2.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio2MouseReleased

    private void btnLaboratorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorio2ActionPerformed
       
        PanelLab2 panel = new PanelLab2();
        
        CambiarPanel(panel);
    }//GEN-LAST:event_btnLaboratorio2ActionPerformed

    private void btnLaboratorio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio3MouseEntered
        btnLaboratorio3.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio3MouseEntered

    private void btnLaboratorio3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio3MouseExited
        btnLaboratorio3.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio3MouseExited

    private void btnLaboratorio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio3MousePressed
        btnLaboratorio3.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio3MousePressed

    private void btnLaboratorio3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio3MouseReleased
        btnLaboratorio3.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio3MouseReleased

    private void btnLaboratorio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorio3ActionPerformed
        PanelLab3 panel = new PanelLab3();
        
        CambiarPanel(panel);
    }//GEN-LAST:event_btnLaboratorio3ActionPerformed
    
    
    //en la funcion del boton inicio oculatamos los botones de los laboratorios y mostramos el panel inicial
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        
        btnLaboratorio1.setVisible(false);
        btnLaboratorio2.setVisible(false);
        btnLaboratorio3.setVisible(false);
        btnLaboratorio4.setVisible(false);
        btnLaboratorio5.setVisible(false);
        
        PanelContencion.removeAll();
        PanelContencion.revalidate();
        PanelContencion.repaint();    
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseClicked
        
        //cuando hace doble click se esconden los botones
        
        if (evt.getClickCount() == 2)
        {
            btnLaboratorio1.setVisible(false);
            btnLaboratorio2.setVisible(false);
            btnLaboratorio3.setVisible(false);
            btnLaboratorio4.setVisible(false);
            btnLaboratorio5.setVisible(false);
            
            PanelContencion.removeAll(); //removeoms lo que hay en el panel
            PanelContencion.revalidate();
            PanelContencion.repaint();   //repintamos
        }
 
    }//GEN-LAST:event_btnLaboratoriosMouseClicked

    private void btnLaboratorio4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio4MouseEntered
         btnLaboratorio4.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio4MouseEntered

    private void btnLaboratorio4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio4MouseExited
         btnLaboratorio4.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio4MouseExited

    private void btnLaboratorio4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio4MousePressed
        btnLaboratorio4.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio4MousePressed

    private void btnLaboratorio4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio4MouseReleased
       btnLaboratorio4.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio4MouseReleased

    private void btnLaboratorio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorio4ActionPerformed
        PanelLab4 panel = new PanelLab4();
        
        CambiarPanel(panel);
    }//GEN-LAST:event_btnLaboratorio4ActionPerformed

    private void btnLaboratorio5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio5MouseEntered
        btnLaboratorio5.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio5MouseEntered

    private void btnLaboratorio5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio5MouseExited
         btnLaboratorio5.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio5MouseExited

    private void btnLaboratorio5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio5MousePressed
        btnLaboratorio5.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnLaboratorio5MousePressed

    private void btnLaboratorio5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratorio5MouseReleased
         btnLaboratorio5.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnLaboratorio5MouseReleased

    private void btnLaboratorio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorio5ActionPerformed
        PanelLab5 panel = new PanelLab5();
        
        CambiarPanel(panel);
    }//GEN-LAST:event_btnLaboratorio5ActionPerformed

    private void btnLaboratorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorio1ActionPerformed
         PanelLab1 panel = new PanelLab1();
        
        CambiarPanel(panel);
    }//GEN-LAST:event_btnLaboratorio1ActionPerformed

    private void CambiarPanel(JPanel panel)
    {
        panel.setSize(600,430); //le damos las medidas del panel
        panel.setLocation(0,0);
        
        PanelContencion.removeAll(); //removeoms lo que hay en el panel
        PanelContencion.add(panel, BorderLayout.CENTER); //agragamos a panel de contencion el nuevo panel a mostrar
        PanelContencion.revalidate();
        PanelContencion.repaint();   //repintamos
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAzul;
    private javax.swing.JPanel PanelContencion;
    private javax.swing.JPanel PanelPresentacion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLaboratorio1;
    private javax.swing.JButton btnLaboratorio2;
    private javax.swing.JButton btnLaboratorio3;
    private javax.swing.JButton btnLaboratorio4;
    private javax.swing.JButton btnLaboratorio5;
    private javax.swing.JButton btnLaboratorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
