package interfaz;


import Laboratorio5.PanelLab5Ejercicio1;
import Laboratorio5.PanelLab5Ejercicio2;
import Laboratorio5.PanelLab5Ejercicio3;
import Laboratorio5.PanelLab5Ejercicio4;
import Laboratorio5.PanelLab5Ejercicio5;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;


/**
 *
 * @author Usuario
 */
public class PanelLab5 extends javax.swing.JPanel {

    /**
     * Creates new form PanelLab5
     */
    public PanelLab5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnProbar = new javax.swing.JButton();
        PanelProbarEjercicio = new javax.swing.JPanel();

        setBackground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel1.setText("Laboratorio de Listas");

        jComboBox1.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejercicio 1", "Ejercicio 2", "Ejercicio 3", "Ejercicio 4", "Ejercicio 5" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnProbar.setBackground(new java.awt.Color(226, 226, 226));
        btnProbar.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnProbar.setText("Probar");
        btnProbar.setBorderPainted(false);
        btnProbar.setContentAreaFilled(false);
        btnProbar.setFocusable(false);
        btnProbar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProbar.setOpaque(true);
        btnProbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProbarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProbarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnProbarMouseReleased(evt);
            }
        });
        btnProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarActionPerformed(evt);
            }
        });

        PanelProbarEjercicio.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout PanelProbarEjercicioLayout = new javax.swing.GroupLayout(PanelProbarEjercicio);
        PanelProbarEjercicio.setLayout(PanelProbarEjercicioLayout);
        PanelProbarEjercicioLayout.setHorizontalGroup(
            PanelProbarEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelProbarEjercicioLayout.setVerticalGroup(
            PanelProbarEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProbar)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
            .addComponent(PanelProbarEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProbar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelProbarEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnProbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProbarMouseEntered
        btnProbar.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnProbarMouseEntered

    private void btnProbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProbarMouseExited
        btnProbar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnProbarMouseExited

    private void btnProbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProbarMousePressed
        btnProbar.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnProbarMousePressed

    private void btnProbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProbarMouseReleased
        btnProbar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnProbarMouseReleased

    private void btnProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarActionPerformed

        String ejercicio = jComboBox1.getSelectedItem().toString();

        switch(ejercicio)
        {
            case "Ejercicio 1":

            PanelLab5Ejercicio1 panel = new PanelLab5Ejercicio1();
            CambiarPanel(panel);

            break;
            case "Ejercicio 2":

            PanelLab5Ejercicio2 panel2 = new PanelLab5Ejercicio2();
            CambiarPanel(panel2);

            break;
            case "Ejercicio 3":

            PanelLab5Ejercicio3 panel3 = new PanelLab5Ejercicio3();
            CambiarPanel(panel3);

            break;
            case "Ejercicio 4":

            PanelLab5Ejercicio4 panel4 = new PanelLab5Ejercicio4();
            CambiarPanel(panel4);

            break;
            case "Ejercicio 5":

            PanelLab5Ejercicio5 panel5 = new PanelLab5Ejercicio5();
            CambiarPanel(panel5);

            break;
        }

    }//GEN-LAST:event_btnProbarActionPerformed

    private void CambiarPanel(JPanel panel)
    {
        panel.setSize(600,430); //le damos las medidas del panel
        panel.setLocation(0,0);
        
        PanelProbarEjercicio.removeAll(); //removeoms lo que hay en el panel
        PanelProbarEjercicio.add(panel, BorderLayout.CENTER); //agragamos a panel de contencion el nuevo panel a mostrar
        PanelProbarEjercicio.revalidate();
        PanelProbarEjercicio.repaint();   //repintamos
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelProbarEjercicio;
    private javax.swing.JButton btnProbar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
