package Laboratorio1;

import static Laboratorio1.ApartamentosOrdenado.Eliminar;
import static Laboratorio1.ApartamentosOrdenado.ImprimirDepartamento;
import static Laboratorio1.ApartamentosOrdenado.Insertar;
import static Laboratorio1.ApartamentosOrdenado.ModifPrecio;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import static java.util.stream.IntStream.range;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PanelOrdenados extends javax.swing.JPanel {
    
    /*Declaramos los atributos como privados para que no se puedan usar en otra clase
     Estos los usaremos para nuestro panel en el que vamos a desarrollar el jercicio de 
    departamentos con arreglos odenados
    */
    private int cantidad_departamentos = 0, n = -1;
    private String ubicaciones[];
    private Integer extensiones[];
    private Integer precios[];
    
    /**
     * Creates new form PanelOrdenados
     */
    public PanelOrdenados() {
        initComponents();
        
        /** Panel departamentos
         * Al iniciar el panel descativamos los radio boton para evitar errores, para ello
         * usamos el método setEnabled para los objetos de tipo radio boton
         */
        btn.setVisible(false);
        jTable.setVisible(false);
        jRadioButton_Rentar1.setEnabled(false);
        jRadioButton_DarDeAlta.setEnabled(false);
        jRadioButton_ActualizarPrecio.setEnabled(false);
        jRadioButton_InfoDepartamento.setEnabled(false);
        jRadioButton_ListarInfo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane_Apartamentos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_ListarInfo = new javax.swing.JRadioButton();
        jRadioButton_DarDeAlta = new javax.swing.JRadioButton();
        jRadioButton_ActualizarPrecio = new javax.swing.JRadioButton();
        jRadioButton_InfoDepartamento = new javax.swing.JRadioButton();
        jRadioButton_Rentar1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField_CantDepartamentos = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(232, 232, 232));

        jTabbedPane_Apartamentos.setBackground(new java.awt.Color(232, 232, 232));
        jTabbedPane_Apartamentos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane_Apartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane_Apartamentos.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTabbedPane_Apartamentos.setName(""); // NOI18N
        jTabbedPane_Apartamentos.setOpaque(true);

        buttonGroup1.add(jRadioButton_ListarInfo);
        jRadioButton_ListarInfo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ListarInfo.setText("Listar información");
        jRadioButton_ListarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListarInfoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_DarDeAlta);
        jRadioButton_DarDeAlta.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_DarDeAlta.setText("Dar de alta");
        jRadioButton_DarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_DarDeAltaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ActualizarPrecio);
        jRadioButton_ActualizarPrecio.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ActualizarPrecio.setText("Actualizar precio");
        jRadioButton_ActualizarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ActualizarPrecioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_InfoDepartamento);
        jRadioButton_InfoDepartamento.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_InfoDepartamento.setText("<html>Informacion de<br>departamento<html>");
        jRadioButton_InfoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InfoDepartamentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Rentar1);
        jRadioButton_Rentar1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_Rentar1.setText("Rentar");
        jRadioButton_Rentar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Rentar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad de departamentos: ");

        btnAgregar.setBackground(new java.awt.Color(226, 226, 226));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setOpaque(true);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregarMouseReleased(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btn.setBackground(new java.awt.Color(226, 226, 226));
        btn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn.setText("Rentar");
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setFocusable(false);
        btn.setOpaque(true);
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMouseReleased(evt);
            }
        });
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setEnabled(false);
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton_Rentar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_DarDeAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_ActualizarPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_InfoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_ListarInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CantDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addComponent(btn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_CantDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_DarDeAlta)
                        .addComponent(jRadioButton_ActualizarPrecio)
                        .addComponent(jRadioButton_InfoDepartamento)
                        .addComponent(jRadioButton_ListarInfo))
                    .addComponent(jRadioButton_Rentar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane_Apartamentos.addTab("Apartamentos", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edificios_1.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jTabbedPane_Apartamentos.addTab("Empleados", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-coworking_1.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Apartamentos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Apartamentos)
        );

        jTabbedPane_Apartamentos.getAccessibleContext().setAccessibleName("tabbed");
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_DarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_DarDeAltaActionPerformed

        btn.setText("Dar de alta");
    }//GEN-LAST:event_jRadioButton_DarDeAltaActionPerformed

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        btnAgregar.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnAgregarMousePressed

    private void btnAgregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseReleased
        btnAgregar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregarMouseReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        try
        {
            cantidad_departamentos = Integer.parseInt(jTextField_CantDepartamentos.getText());
            ubicaciones = new String[cantidad_departamentos];
            extensiones = new Integer[cantidad_departamentos];
            precios = new Integer[cantidad_departamentos];
            jRadioButton_Rentar1.setEnabled(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ingrese la cantidad de departamentos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        btn.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnMouseEntered

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        btn.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnMouseExited

    private void btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMousePressed
        btn.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnMousePressed

    private void btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseReleased
        btn.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnMouseReleased

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
       /*
        Al ocurrir el click en el boton usamos estructuras de selcci[on, si el radio boton rentar esta seleccionado
        entonces ejecutamos la funcion insertar, en caso de que el arreglo todav[ia est[e vacio se mantienen desactivados 
        los dem[as radio boton est[an desactivados 
        */     
       if (jRadioButton_Rentar1.isSelected() == true)
       {
           n = Insertar(ubicaciones, extensiones, precios, n, cantidad_departamentos);

           if (n > -1) 
           {
               jRadioButton_DarDeAlta.setEnabled(true);
               jRadioButton_ActualizarPrecio.setEnabled(true);
               jRadioButton_InfoDepartamento.setEnabled(true);
               jRadioButton_ListarInfo.setEnabled(true);
           }
       }
       else if (jRadioButton_DarDeAlta.isSelected() == true)
       {
           n = Eliminar(ubicaciones, extensiones, precios, n);
           
            if (n < 0)
           {    
               jRadioButton_DarDeAlta.setEnabled(false);
               jRadioButton_ActualizarPrecio.setEnabled(false);
               jRadioButton_InfoDepartamento.setEnabled(false);
               jRadioButton_ListarInfo.setEnabled(false);
           }
       }
       else if (jRadioButton_ActualizarPrecio.isSelected() == true)
       {
           ModifPrecio(ubicaciones, extensiones, precios, n);
       }
       else if ( jRadioButton_InfoDepartamento.isSelected() == true)
       {
           ImprimirDepartamento(ubicaciones, extensiones, precios, n);
           
       }
       else if (jRadioButton_ListarInfo.isSelected() == true)
       {          
           jTable.setVisible(true);
           
           DefaultTableModel modelo =  new DefaultTableModel();
           ArrayList<Object[]> lista = new ArrayList<>(); 
           
           modelo.addColumn("Ubicacion"); //al modelo por default le agregamos una columnas llamada valores
           modelo.addColumn("Extension");
           modelo.addColumn("Precio");
           
           if (n > -1)
           {  
               /*
               Procedemos a llenar la lista con los datos actualizados, usamos un Object para llenar la lista              
               */ 
               for (int i = 0; i <= n; i++) 
               {
                   Object[] fila = new Object[]{ubicaciones[i], extensiones[i], precios[i]};

                   if (ubicaciones[i] != null && extensiones[i] != null && precios[i] != null) 
                   {
                       lista.add(fila);
                   }
               }

               for (Object[] informacion : lista) 
               {
                   modelo.addRow(informacion);
               }
               
               jTable.setModel(modelo);//mostramos la tabla con este modelo que creamos  
           }
           else
           {
               for (int i = 1; i <= lista.size(); i++)
               {
                   modelo.removeRow(i);
               }
               
               jTable.setModel(modelo);
               lista.removeAll(lista);
               JOptionPane.showMessageDialog(null,"Array vacío");
           }
            
        }
    }//GEN-LAST:event_btnActionPerformed

    private void jRadioButton_Rentar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Rentar1ActionPerformed
        btn.setVisible(true);
        btn.setText("Rentar");
        jTable.setVisible(false);
    }//GEN-LAST:event_jRadioButton_Rentar1ActionPerformed

    private void jRadioButton_ActualizarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ActualizarPrecioActionPerformed
        btn.setText("Actualizar Precio");
        jTable.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ActualizarPrecioActionPerformed

    private void jRadioButton_InfoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InfoDepartamentoActionPerformed
        btn.setText("Informacion de departamento");
        jTable.setVisible(false);
    }//GEN-LAST:event_jRadioButton_InfoDepartamentoActionPerformed

    private void jRadioButton_ListarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListarInfoActionPerformed
        btn.setText("Listar Informacion");
        jTable.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ListarInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_ActualizarPrecio;
    private javax.swing.JRadioButton jRadioButton_DarDeAlta;
    private javax.swing.JRadioButton jRadioButton_InfoDepartamento;
    private javax.swing.JRadioButton jRadioButton_ListarInfo;
    private javax.swing.JRadioButton jRadioButton_Rentar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane_Apartamentos;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_CantDepartamentos;
    // End of variables declaration//GEN-END:variables
}
