
package Laboratorio1;

import static Laboratorio1.AlumnosDesordenados.EliminarAlumnos;
import static Laboratorio1.AlumnosDesordenados.InsertarAlumnos;
import static Laboratorio1.AlumnosDesordenados.ListarAlumno;
import static Laboratorio1.AlumnosDesordenados.ModificarAlumno;
import static Laboratorio1.EmpleadosDesordenados.EliminarEmpleados;
import static Laboratorio1.EmpleadosDesordenados.InsertarEmpleados;
import static Laboratorio1.EmpleadosDesordenados.ListarEmpleado;
import static Laboratorio1.EmpleadosDesordenados.ModificarEmpleados;
import static Laboratorio1.EmpresaDesordenados.EliminarCliente;
import static Laboratorio1.EmpresaDesordenados.InsertarClientes;
import static Laboratorio1.EmpresaDesordenados.ListarCliente;
import static Laboratorio1.EmpresaDesordenados.ModificarCliente;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PanelDesordenados extends javax.swing.JPanel {

    /**
     * Creates new form PanelDesordenados
     */
    
    int cant_alumnos = 0, n1 = -1;
    String nombres_alumnos[];
    Double promedios_alumnos[];
    Integer semestres_alumnos[];
    
    int cant_clientes = 0, n2 = -1;
    String nombres_clientes[];
    Integer telefonos_clientes[];
    Double saldos_clientes[];
    Integer morosos_clientes[];
    
    int cant_empleados = 0, n3 = -1;
    String nombres_empleados[];
    Integer edades_empleados[];
    String sexos_empleados[];
    
    
    public PanelDesordenados() {
        initComponents();
        
        btn.setVisible(false);
        jTable1.setVisible(false);
        jRadioButton_RegistrarA.setEnabled(false);
        jRadioButton_ModificarA.setEnabled(false);
        jRadioButton_ListarInfoA.setEnabled(false);
        jRadioButton_InfoA.setEnabled(false);
        jRadioButton_EliminarA.setEnabled(false);
        
        btn2.setVisible(false);
        jTable2.setVisible(false);
        jRadioButton_RegistrarC.setEnabled(false);
        jRadioButton_ModificarC.setEnabled(false);
        jRadioButton_ListarInfoC.setEnabled(false);
        jRadioButton_InfoC.setEnabled(false);
        jRadioButton_EliminarC.setEnabled(false);
        
        btn3.setVisible(false);
        jTable3.setVisible(false);
        jRadioButton_RegistrarE.setEnabled(false);
        jRadioButton_ActualizarE.setEnabled(false);
        jRadioButton_ListarInfoMasculinos.setEnabled(false);
        jRadioButton_InfoE.setEnabled(false);
        jRadioButton_EliminarE.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton_ListarInfoA = new javax.swing.JRadioButton();
        jRadioButton_EliminarA = new javax.swing.JRadioButton();
        jRadioButton_ModificarA = new javax.swing.JRadioButton();
        jRadioButton_InfoA = new javax.swing.JRadioButton();
        jRadioButton_RegistrarA = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField_CantAlumnos = new javax.swing.JTextField();
        btnAgregar_Alumnos = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton_ListarInfoC = new javax.swing.JRadioButton();
        jRadioButton_EliminarC = new javax.swing.JRadioButton();
        jRadioButton_ModificarC = new javax.swing.JRadioButton();
        jRadioButton_InfoC = new javax.swing.JRadioButton();
        jRadioButton_RegistrarC = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField_CantClientes = new javax.swing.JTextField();
        btnAgregar_Clientes = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton_ListarInfoMasculinos = new javax.swing.JRadioButton();
        jRadioButton_EliminarE = new javax.swing.JRadioButton();
        jRadioButton_ActualizarE = new javax.swing.JRadioButton();
        jRadioButton_InfoE = new javax.swing.JRadioButton();
        jRadioButton_RegistrarE = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField_CantEmpleados = new javax.swing.JTextField();
        btnAgregar_Empleados = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        buttonGroup1.add(jRadioButton_ListarInfoA);
        jRadioButton_ListarInfoA.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ListarInfoA.setText("Listar info");
        jRadioButton_ListarInfoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListarInfoAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_EliminarA);
        jRadioButton_EliminarA.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_EliminarA.setText("Eliminar");
        jRadioButton_EliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EliminarAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ModificarA);
        jRadioButton_ModificarA.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ModificarA.setText("<html>Modificar semestre<br>y promedio<html>");
        jRadioButton_ModificarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ModificarAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_InfoA);
        jRadioButton_InfoA.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_InfoA.setText("<html>Informacion de<br>alumno<html>");
        jRadioButton_InfoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InfoAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_RegistrarA);
        jRadioButton_RegistrarA.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_RegistrarA.setText("Registrar");
        jRadioButton_RegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_RegistrarAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad de alumnos: ");

        btnAgregar_Alumnos.setBackground(new java.awt.Color(226, 226, 226));
        btnAgregar_Alumnos.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnAgregar_Alumnos.setText("Agregar");
        btnAgregar_Alumnos.setBorderPainted(false);
        btnAgregar_Alumnos.setContentAreaFilled(false);
        btnAgregar_Alumnos.setFocusable(false);
        btnAgregar_Alumnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar_Alumnos.setOpaque(true);
        btnAgregar_Alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar_Alumnos_DepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar_Alumnos_DepartamentosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregar_Alumnos_DepartamentosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregar_Alumnos_DepartamentosMouseReleased(evt);
            }
        });
        btnAgregar_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_Alumnos_DepartamentosActionPerformed(evt);
            }
        });

        btn.setBackground(new java.awt.Color(226, 226, 226));
        btn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn.setText("Rentar");
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setFocusable(false);
        btn.setOpaque(true);
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMouseReleased(evt);
            }
        });
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CantAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar_Alumnos))
                            .addComponent(btn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton_RegistrarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_EliminarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_ModificarA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_InfoA, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_ListarInfoA)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_CantAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar_Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_EliminarA)
                        .addComponent(jRadioButton_ModificarA)
                        .addComponent(jRadioButton_InfoA)
                        .addComponent(jRadioButton_ListarInfoA))
                    .addComponent(jRadioButton_RegistrarA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 62, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Alumnos", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-estudiantes-2.png")), jPanel1); // NOI18N

        buttonGroup1.add(jRadioButton_ListarInfoC);
        jRadioButton_ListarInfoC.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ListarInfoC.setText("Listar info");
        jRadioButton_ListarInfoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListarInfoCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_EliminarC);
        jRadioButton_EliminarC.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_EliminarC.setText("Eliminar");
        jRadioButton_EliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EliminarCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ModificarC);
        jRadioButton_ModificarC.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ModificarC.setText("<html>Modificar estado<br>de deuda<html>");
        jRadioButton_ModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ModificarCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_InfoC);
        jRadioButton_InfoC.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_InfoC.setText("<html>Informacion de<br>alumno<html>");
        jRadioButton_InfoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InfoCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_RegistrarC);
        jRadioButton_RegistrarC.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_RegistrarC.setText("Registrar");
        jRadioButton_RegistrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_RegistrarCActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad de clientes: ");

        btnAgregar_Clientes.setBackground(new java.awt.Color(226, 226, 226));
        btnAgregar_Clientes.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnAgregar_Clientes.setText("Agregar");
        btnAgregar_Clientes.setBorderPainted(false);
        btnAgregar_Clientes.setContentAreaFilled(false);
        btnAgregar_Clientes.setFocusable(false);
        btnAgregar_Clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar_Clientes.setOpaque(true);
        btnAgregar_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar_Clientes_DepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar_Clientes_DepartamentosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregar_Clientes_DepartamentosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregar_Clientes_DepartamentosMouseReleased(evt);
            }
        });
        btnAgregar_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_Clientes_DepartamentosActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(226, 226, 226));
        btn2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn2.setText("Rentar");
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setFocusable(false);
        btn2.setOpaque(true);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn2MouseReleased(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar_Clientes))
                            .addComponent(btn2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadioButton_RegistrarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_EliminarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_ModificarC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_InfoC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_ListarInfoC)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_CantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_EliminarC)
                        .addComponent(jRadioButton_ModificarC)
                        .addComponent(jRadioButton_InfoC)
                        .addComponent(jRadioButton_ListarInfoC))
                    .addComponent(jRadioButton_RegistrarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 62, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Clientes", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clientes.png")), jPanel2); // NOI18N

        buttonGroup1.add(jRadioButton_ListarInfoMasculinos);
        jRadioButton_ListarInfoMasculinos.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ListarInfoMasculinos.setText("<html>Listar Empleados<br>Masculinos<html>");
        jRadioButton_ListarInfoMasculinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListarInfoMasculinosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_EliminarE);
        jRadioButton_EliminarE.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_EliminarE.setText("Eliminar");
        jRadioButton_EliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EliminarEActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ActualizarE);
        jRadioButton_ActualizarE.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_ActualizarE.setText("Actualizar edad");
        jRadioButton_ActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ActualizarEActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_InfoE);
        jRadioButton_InfoE.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_InfoE.setText("<html>Informacion de<br>empleado<html>");
        jRadioButton_InfoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InfoEActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_RegistrarE);
        jRadioButton_RegistrarE.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioButton_RegistrarE.setText("Registrar");
        jRadioButton_RegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_RegistrarEActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad de empleados: ");

        jTextField_CantEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CantEmpleadosActionPerformed(evt);
            }
        });

        btnAgregar_Empleados.setBackground(new java.awt.Color(226, 226, 226));
        btnAgregar_Empleados.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnAgregar_Empleados.setText("Agregar");
        btnAgregar_Empleados.setBorderPainted(false);
        btnAgregar_Empleados.setContentAreaFilled(false);
        btnAgregar_Empleados.setFocusable(false);
        btnAgregar_Empleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar_Empleados.setOpaque(true);
        btnAgregar_Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar_Empleados_DepartamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar_Empleados_DepartamentosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregar_Empleados_DepartamentosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregar_Empleados_DepartamentosMouseReleased(evt);
            }
        });
        btnAgregar_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_Empleados_DepartamentosActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(226, 226, 226));
        btn3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn3.setText("Rentar");
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setFocusable(false);
        btn3.setOpaque(true);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn3MouseReleased(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        jTable3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setEnabled(false);
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregar_Empleados))
                                    .addComponent(btn3)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_RegistrarE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_EliminarE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_ActualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_InfoE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_ListarInfoMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)))
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_EliminarE)
                        .addComponent(jRadioButton_ActualizarE)
                        .addComponent(jRadioButton_InfoE)
                        .addComponent(jRadioButton_ListarInfoMasculinos))
                    .addComponent(jRadioButton_RegistrarE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 62, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Empleados", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sala-de-reuniones.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_ListarInfoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListarInfoAActionPerformed
        btn.setText("Listar Informacion");
        jTable1.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ListarInfoAActionPerformed

    private void jRadioButton_EliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EliminarAActionPerformed

        btn.setText("Eliminar");
    }//GEN-LAST:event_jRadioButton_EliminarAActionPerformed

    private void jRadioButton_ModificarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModificarAActionPerformed
        btn.setText("Modificar Info");
        jTable1.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ModificarAActionPerformed

    private void jRadioButton_InfoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InfoAActionPerformed
        btn.setText("Informacion de alumno");
        jTable1.setVisible(false);
    }//GEN-LAST:event_jRadioButton_InfoAActionPerformed

    private void jRadioButton_RegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_RegistrarAActionPerformed
        btn.setVisible(true);
        btn.setText("Registrar");
        jTable1.setVisible(false);
    }//GEN-LAST:event_jRadioButton_RegistrarAActionPerformed

    private void btnAgregar_Alumnos_DepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Alumnos_DepartamentosMouseEntered
        btnAgregar_Alumnos.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnAgregar_Alumnos_DepartamentosMouseEntered

    private void btnAgregar_Alumnos_DepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Alumnos_DepartamentosMouseExited
        btnAgregar_Alumnos.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Alumnos_DepartamentosMouseExited

    private void btnAgregar_Alumnos_DepartamentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Alumnos_DepartamentosMousePressed
        btnAgregar_Alumnos.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnAgregar_Alumnos_DepartamentosMousePressed

    private void btnAgregar_Alumnos_DepartamentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Alumnos_DepartamentosMouseReleased
        btnAgregar_Alumnos.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Alumnos_DepartamentosMouseReleased

    private void btnAgregar_Alumnos_DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_Alumnos_DepartamentosActionPerformed

        try
        {
            cant_alumnos = Integer.parseInt(jTextField_CantAlumnos.getText());
            nombres_alumnos= new String[cant_alumnos];
            promedios_alumnos = new Double[cant_alumnos];
            semestres_alumnos = new Integer[cant_alumnos];
            jRadioButton_RegistrarA.setEnabled(true);
            jTextField_CantAlumnos.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ingrese la cantidad de Alumnos");
        }
    }//GEN-LAST:event_btnAgregar_Alumnos_DepartamentosActionPerformed

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        btn.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnMouseEntered

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        btn.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnMouseExited

    private void btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMousePressed
        btn.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnMousePressed

    private void btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseReleased
        btn.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnMouseReleased

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        /*
        Al ocurrir el click en el boton usamos estructuras de selcci[on, si el radio boton rentar esta seleccionado
        entonces ejecutamos la funcion insertar, en caso de que el arreglo todav[ia est[e vacio se mantienen desactivados
        los dem[as radio boton est[an desactivados
        */
        if (jRadioButton_RegistrarA.isSelected() == true)
        {
            n1 = InsertarAlumnos(nombres_alumnos, semestres_alumnos,promedios_alumnos,n1,cant_alumnos);

            if (n1 > -1)
            {
                jRadioButton_ModificarA.setEnabled(true);
                jRadioButton_ListarInfoA.setEnabled(true);
                jRadioButton_InfoA.setEnabled(true);
                jRadioButton_EliminarA.setEnabled(true);
            }
        }
        else if (jRadioButton_EliminarA.isSelected() == true)
        {
            n1 = EliminarAlumnos(nombres_alumnos, semestres_alumnos, promedios_alumnos, n1);

            if (n1 < 0)
            {
                jRadioButton_RegistrarA.setEnabled(false);
                jRadioButton_ModificarA.setEnabled(false);
                jRadioButton_InfoA.setEnabled(false);
                jRadioButton_ListarInfoA.setEnabled(false);
            }
            
            jTable1.setVisible(false);
        }
        else if (jRadioButton_ModificarA.isSelected() == true)
        {
            ModificarAlumno(nombres_alumnos,semestres_alumnos, promedios_alumnos, n1);
        }
        else if (jRadioButton_InfoA.isSelected() == true)
        {
            ListarAlumno(nombres_alumnos,semestres_alumnos, promedios_alumnos, n1);

        }
        else if (jRadioButton_ListarInfoA.isSelected() == true)
        {
            jTable1.setVisible(true);

            DefaultTableModel modelo =  new DefaultTableModel();
            ArrayList<Object[]> lista = new ArrayList<>();

            modelo.addColumn("Nombre"); //al modelo por default le agregamos una columnas llamada valores
            modelo.addColumn("Semestres");
            modelo.addColumn("Promedio");

            if (n1 > -1)
            {
                /*
                Procedemos a llenar la lista con los datos actualizados, usamos un Object para llenar la lista
                */
                for (int i = 0; i <= n1; i++)
                {
                    Object[] fila = new Object[]{nombres_alumnos[i],semestres_alumnos[i], promedios_alumnos[i]};

                    if (nombres_alumnos[i] != null && semestres_alumnos[i] != null && promedios_alumnos[i] != null)
                    {
                        lista.add(fila);
                    }
                }

                for (Object[] informacion : lista)
                {
                    modelo.addRow(informacion);
                }

                jTable1.setModel(modelo);//mostramos la tabla con este modelo que creamos
            }
            else
            {
                for (int i = 1; i <= lista.size(); i++)
                {
                    modelo.removeRow(i);
                }

                jTable1.setModel(modelo);
                lista.removeAll(lista);
                JOptionPane.showMessageDialog(null,"Array vacío");
            }

        }
    }//GEN-LAST:event_btnActionPerformed

    /*
    **********Funciones panel Clientes************
    */
    private void jRadioButton_ListarInfoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListarInfoCActionPerformed
        btn2.setText("Listar Informacion");
        jTable2.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ListarInfoCActionPerformed

    private void jRadioButton_EliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EliminarCActionPerformed
         btn2.setText("Eliminar");
    }//GEN-LAST:event_jRadioButton_EliminarCActionPerformed

    private void jRadioButton_ModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModificarCActionPerformed
        btn2.setText("Modificar Info");
        jTable2.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ModificarCActionPerformed

    private void jRadioButton_InfoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InfoCActionPerformed
        btn2.setText("Informacion de cliente");
        jTable2.setVisible(false);
    }//GEN-LAST:event_jRadioButton_InfoCActionPerformed

    private void jRadioButton_RegistrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_RegistrarCActionPerformed
        btn2.setVisible(true);
        btn2.setText("Registrar");
        jTable2.setVisible(false);
    }//GEN-LAST:event_jRadioButton_RegistrarCActionPerformed

    private void btnAgregar_Clientes_DepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Clientes_DepartamentosMouseEntered
        btnAgregar_Clientes.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnAgregar_Clientes_DepartamentosMouseEntered

    private void btnAgregar_Clientes_DepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Clientes_DepartamentosMouseExited
        btnAgregar_Clientes.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Clientes_DepartamentosMouseExited

    private void btnAgregar_Clientes_DepartamentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Clientes_DepartamentosMousePressed
        btnAgregar_Clientes.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnAgregar_Clientes_DepartamentosMousePressed

    private void btnAgregar_Clientes_DepartamentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Clientes_DepartamentosMouseReleased
        btnAgregar_Clientes.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Clientes_DepartamentosMouseReleased

    private void btnAgregar_Clientes_DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_Clientes_DepartamentosActionPerformed
       
        try
        {
            cant_clientes = Integer.parseInt(jTextField_CantClientes.getText());
            nombres_clientes = new String[cant_clientes];
            telefonos_clientes = new Integer[cant_clientes];
            saldos_clientes = new Double[cant_clientes];
            morosos_clientes = new Integer[cant_clientes];
            
            jRadioButton_RegistrarC.setEnabled(true);
            jTextField_CantClientes.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ingrese la cantidad de Clientes");
        }
    }//GEN-LAST:event_btnAgregar_Clientes_DepartamentosActionPerformed

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        btn2.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btn2MouseEntered

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btn2MouseExited

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        btn2.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btn2MousePressed

    private void btn2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseReleased
        btn2.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btn2MouseReleased

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        if (jRadioButton_RegistrarC.isSelected() == true)
        {
            n2 = InsertarClientes(nombres_clientes, telefonos_clientes,saldos_clientes,morosos_clientes,n2,cant_clientes);

            if (n2 > -1)
            {
                jRadioButton_ModificarC.setEnabled(true);
                jRadioButton_ListarInfoC.setEnabled(true);
                jRadioButton_InfoC.setEnabled(true);
                jRadioButton_EliminarC.setEnabled(true);
            }
        }
        else if (jRadioButton_EliminarC.isSelected() == true)
        {
            n2 = EliminarCliente(nombres_clientes, telefonos_clientes,saldos_clientes,morosos_clientes,n2,cant_clientes);

            if (n2 < 0)
            {
                jRadioButton_EliminarC.setEnabled(false);
                jRadioButton_ModificarC.setEnabled(false);
                jRadioButton_InfoC.setEnabled(false);
                jRadioButton_ListarInfoC.setEnabled(false);  
            }
            
            jTable2.setVisible(false);
        }
        else if (jRadioButton_ModificarC.isSelected() == true)
        {
            ModificarCliente(nombres_clientes, telefonos_clientes,saldos_clientes,morosos_clientes,n2,cant_clientes);
        }
        else if (jRadioButton_InfoC.isSelected() == true)
        {
            ListarCliente(nombres_clientes, telefonos_clientes,saldos_clientes,morosos_clientes,n2,cant_clientes);

        }
        else if (jRadioButton_ListarInfoC.isSelected() == true)
        {
            jTable2.setVisible(true);

            DefaultTableModel modelo =  new DefaultTableModel();
            ArrayList<Object[]> lista = new ArrayList<>();

            modelo.addColumn("Nombre"); //al modelo por default le agregamos una columnas llamada valores
            modelo.addColumn("Telefono");
            modelo.addColumn("Saldo");
            modelo.addColumn("Debe");
            
            Object[] fila = new Object[]{null,null,null,null};
            
            if (n2 > -1)
            {
                /*
                Procedemos a llenar la lista con los datos actualizados, usamos un Object para llenar la lista
                */
                for (int i = 0; i <= n2; i++)
                {
                    
                   if (morosos_clientes[i] == 0)
                   {
                      fila = new Object[]{nombres_clientes[i],telefonos_clientes[i], saldos_clientes[i],
                                                    "Debe"};
                   }
                   else if(morosos_clientes[i] == 1)
                   {
                      fila = new Object[]{nombres_clientes[i],telefonos_clientes[i], saldos_clientes[i],
                                                    "No Debe"};
                   }

                   lista.add(fila);
                }

                for (Object[] informacion : lista)
                {
                    modelo.addRow(informacion);
                }

                jTable2.setModel(modelo);//mostramos la tabla con este modelo que creamos
            }
            else
            {
                for (int i = 1; i <= lista.size(); i++)
                {
                    modelo.removeRow(i);
                }

                jTable2.setModel(modelo);
                lista.removeAll(lista);
                JOptionPane.showMessageDialog(null,"Array vacío");
            }

        }
    }//GEN-LAST:event_btn2ActionPerformed

    /*******************Funciones Panel Empleados****************************/
    
    private void jRadioButton_ListarInfoMasculinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListarInfoMasculinosActionPerformed
        btn3.setText("Listar Masculinos");
        jTable3.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ListarInfoMasculinosActionPerformed

    private void jRadioButton_EliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EliminarEActionPerformed
        btn3.setText("Eliminar");
    }//GEN-LAST:event_jRadioButton_EliminarEActionPerformed

    private void jRadioButton_ActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ActualizarEActionPerformed
        btn3.setText("Modificar Edad");
        jTable3.setVisible(false);
    }//GEN-LAST:event_jRadioButton_ActualizarEActionPerformed

    private void jRadioButton_InfoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InfoEActionPerformed
        btn3.setText("Informacion de empleado");
        jTable3.setVisible(false);
    }//GEN-LAST:event_jRadioButton_InfoEActionPerformed

    private void jRadioButton_RegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_RegistrarEActionPerformed
        btn3.setVisible(true);
        btn3.setText("Registrar");
        jTable3.setVisible(false);
    }//GEN-LAST:event_jRadioButton_RegistrarEActionPerformed

    private void btnAgregar_Empleados_DepartamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Empleados_DepartamentosMouseEntered
        btnAgregar_Empleados.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnAgregar_Empleados_DepartamentosMouseEntered

    private void btnAgregar_Empleados_DepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Empleados_DepartamentosMouseExited
        btnAgregar_Empleados.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Empleados_DepartamentosMouseExited

    private void btnAgregar_Empleados_DepartamentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Empleados_DepartamentosMousePressed
        btnAgregar_Empleados.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnAgregar_Empleados_DepartamentosMousePressed

    private void btnAgregar_Empleados_DepartamentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar_Empleados_DepartamentosMouseReleased
        btnAgregar_Empleados.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnAgregar_Empleados_DepartamentosMouseReleased

    private void btnAgregar_Empleados_DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_Empleados_DepartamentosActionPerformed
        
        try
        {
            cant_empleados = Integer.parseInt(jTextField_CantEmpleados.getText());
            nombres_empleados = new String[cant_empleados];
            edades_empleados = new Integer[cant_empleados];
            sexos_empleados = new String[cant_empleados];
            jRadioButton_RegistrarE.setEnabled(true);
            
            jTextField_CantEmpleados.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ingrese la cantidad de Empleados");
        }
    }//GEN-LAST:event_btnAgregar_Empleados_DepartamentosActionPerformed

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        btn3.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btn3MouseExited

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        btn3.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btn3MousePressed

    private void btn3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseReleased
        btn3.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btn3MouseReleased

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        
        if (jRadioButton_RegistrarE.isSelected() == true)
        {
            n3 = InsertarEmpleados(nombres_empleados, edades_empleados, sexos_empleados,n3,cant_empleados);

            if (n3 > -1)
            {
                jRadioButton_ActualizarE.setEnabled(true);
                jRadioButton_InfoE.setEnabled(true);
                jRadioButton_ListarInfoMasculinos.setEnabled(true);
                jRadioButton_EliminarE.setEnabled(true);
            }
        }
        else if (jRadioButton_EliminarE.isSelected() == true)
        {
            n3 = EliminarEmpleados(nombres_empleados, edades_empleados,sexos_empleados,n3,cant_empleados);

            if (n3 < 0)
            {
                jRadioButton_EliminarE.setEnabled(false);
                jRadioButton_ActualizarE.setEnabled(false);
                jRadioButton_InfoE.setEnabled(false);
                jRadioButton_ListarInfoMasculinos.setEnabled(false);  
            }
            
            jTable3.setVisible(false);
        }
        else if (jRadioButton_ActualizarE.isSelected() == true)
        {
            ModificarEmpleados(nombres_empleados, edades_empleados,sexos_empleados,n3,cant_empleados);
        }
        else if (jRadioButton_InfoE.isSelected() == true)
        {
            ListarEmpleado(nombres_empleados, edades_empleados,sexos_empleados,n3,cant_empleados);

        }
        else if (jRadioButton_ListarInfoMasculinos.isSelected() == true)
        {
            jTable3.setVisible(true);

            DefaultTableModel modelo =  new DefaultTableModel();
            ArrayList<Object[]> lista = new ArrayList<>();

            modelo.addColumn("Nombre"); //al modelo por default le agregamos una columnas llamada valores
            modelo.addColumn("Edad");
            modelo.addColumn("Sexo");
            
            Object[] fila = new Object[]{null,null,null};
            
            if (n3 > -1)
            {
                /*
                Procedemos a llenar la lista con los datos actualizados, usamos un Object para llenar la lista
                */
                for (int i = 0; i <= n3; i++)
                {
                    
                   if (sexos_empleados[i].equalsIgnoreCase("masculino") )
                   {
                      fila = new Object[]{nombres_empleados[i],edades_empleados[i], sexos_empleados[i]};
                      lista.add(fila);
                   }  
                }

                for (Object[] informacion : lista)
                {
                    modelo.addRow(informacion);
                }

                jTable3.setModel(modelo);//mostramos la tabla con este modelo que creamos
            }
            else
            {
                for (int i = 1; i <= lista.size(); i++)
                {
                    modelo.removeRow(i);
                }

                jTable3.setModel(modelo);
                lista.removeAll(lista);
                JOptionPane.showMessageDialog(null,"Array vacío");
            }

        }
    
    }//GEN-LAST:event_btn3ActionPerformed

    
    private void jTextField_CantEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CantEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CantEmpleadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnAgregar_Alumnos;
    private javax.swing.JButton btnAgregar_Clientes;
    private javax.swing.JButton btnAgregar_Empleados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton_ActualizarE;
    private javax.swing.JRadioButton jRadioButton_EliminarA;
    private javax.swing.JRadioButton jRadioButton_EliminarC;
    private javax.swing.JRadioButton jRadioButton_EliminarE;
    private javax.swing.JRadioButton jRadioButton_InfoA;
    private javax.swing.JRadioButton jRadioButton_InfoC;
    private javax.swing.JRadioButton jRadioButton_InfoE;
    private javax.swing.JRadioButton jRadioButton_ListarInfoA;
    private javax.swing.JRadioButton jRadioButton_ListarInfoC;
    private javax.swing.JRadioButton jRadioButton_ListarInfoMasculinos;
    private javax.swing.JRadioButton jRadioButton_ModificarA;
    private javax.swing.JRadioButton jRadioButton_ModificarC;
    private javax.swing.JRadioButton jRadioButton_RegistrarA;
    private javax.swing.JRadioButton jRadioButton_RegistrarC;
    private javax.swing.JRadioButton jRadioButton_RegistrarE;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField_CantAlumnos;
    private javax.swing.JTextField jTextField_CantClientes;
    private javax.swing.JTextField jTextField_CantEmpleados;
    // End of variables declaration//GEN-END:variables
}
