package Laboratorio5;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class PanelLab5Ejercicio4 extends javax.swing.JPanel {

    /**
     * Creamos la lista y el modelo de la tabla que ocuparemos para este ejercicio
     */
    DefaultTableModel modelo =  new DefaultTableModel();
    ArrayList<String> lista = new ArrayList<>();
    
    public PanelLab5Ejercicio4() {
        initComponents();
        modelo.addColumn("Valores"); //al modelo por default le agregamos una columnas llamada valores
        jTablePilas.setModel(modelo);//mostramos la tabla con este modelo que creamos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textIngresado = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePilas = new javax.swing.JTable();

        setBackground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa un valor :");

        textIngresado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        btnInsertar.setBackground(new java.awt.Color(226, 226, 226));
        btnInsertar.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setBorderPainted(false);
        btnInsertar.setContentAreaFilled(false);
        btnInsertar.setFocusable(false);
        btnInsertar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInsertar.setOpaque(true);
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInsertarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInsertarMouseReleased(evt);
            }
        });
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(226, 226, 226));
        btnEliminar.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar.setOpaque(true);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTablePilas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pila"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePilas.setEnabled(false);
        jScrollPane2.setViewportView(jTablePilas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnInsertar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseEntered
        btnInsertar.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnInsertarMouseEntered

    private void btnInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseExited
        btnInsertar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnInsertarMouseExited

    private void btnInsertarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMousePressed
        btnInsertar.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnInsertarMousePressed

    private void btnInsertarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseReleased
        btnInsertar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnInsertarMouseReleased
    
    /**
     * Tomamos el valor ingresado por el usuario y lo agreamos a la lista con add(valor) eneste caso muestra 
     * lista es para tipos string, sabemos que para agregar una nueva fila le debemos pasar un vector a la 
     * funcion addRow, entonces creamos un vector de tipo string con el valor del ultimo elemento agregado a la 
     * lista, con get() conseguimos el elemento y con size() la longitud de la lista si le restamos un 1 
     * encontramos el ultimo valor agregado
     * 
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
          String cadena = textIngresado.getText();
          lista.add(cadena);
          String [] cadena2 = new String[1];
          cadena2[0] = lista.get(lista.size()-1);
          modelo.addRow(cadena2); //agregamos una fila con los datos de cadena2 a nuestro modelo que estamos creando
          jTablePilas.setModel(modelo);  //mostramos nuestro modelo de la tabla en el jtable
          textIngresado.setText(""); 
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(59,89,152));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        btnEliminar.setBackground(new Color(1,50,170));
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
        btnEliminar.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       textIngresado.setText("");
        try
       {
            lista.remove(lista.get(lista.size()-1)); //borramos el ultimo elemento de la lista
            modelo.removeRow(lista.size()); //a nuestro modelo le borramos la fila donde se encuentra el ultimo elemento
            jTablePilas.setModel(modelo);
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null,"La lista está vacía\nIngrese valores para eliminar");
       }  
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePilas;
    private javax.swing.JTextField textIngresado;
    // End of variables declaration//GEN-END:variables
}
